development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: pactoultraview
  :password: teampactorules
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: pactoultraview
  :password: teampactorules
  :enable_starttls_auto: true